# Generated by Django 5.2.6 on 2025-09-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
